# Generated by Django 4.1.6 on 2023-02-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='produce_from',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
