# Generated by Django 4.1.6 on 2023-02-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_image_product_image1_product_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
    ]
