# Generated by Django 4.1.6 on 2023-02-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_product_image2_remove_product_image3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image1',
            new_name='image',
        ),
    ]
