# Generated by Django 4.1.6 on 2023-02-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_rename_image1_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='produce_from',
            new_name='product_from',
        ),
    ]
