# Generated by Django 4.1.6 on 2023-03-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_image2_product_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='users',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
